baseURL = 'https://henriqueleaop.github.io/blog/'
locale = 'pt-br'
title = 'Obscura'
theme = 'PaperMod'

[params]
    env = "production"
    disableHLJS = false
    showShareButtons = false
    showPostNavLinks = true